baseurl = "https://chihaya.io"
title = "chihaya"
languageCode = "en-us"
theme = "hugo-material-docs"

[params]
  description = "A customizible, multi-protocol BitTorrent Tracker"
  copyright = "Chihaya Authors. Released under the BSD 2-Clause License"
  logo = "img/logo.png"
  provider = "GitHub"
  repo_url = "https://github.com/chihaya/chihaya"
  googleAnalytics = "UA-86385626-1"

[params.palette]
  primary = "blue"
  accent = "light-blue"

[social]
  github = "chihaya"

[blackfriday]
  smartypants = true
  fractions = true
  smartDashes = true
  plainIDAnchors = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 0

[[menu.main]]
  name = "Changelog"
  url = "https://github.com/chihaya/chihaya/releases"
  weight = 1

[[menu.main]]
  name = "v2 Documentation"
  url = "/"
  weight = 2

[[menu.main]]
  name = "v1 Documentation"
  url = "/"
  weight = 3
